name: fruit_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluttertoast: ^7.1.1
  model: ^0.0.3

  flutter:
    sdk: flutter
  path_provider: ^1.6.14
  sqflite: ^1.3.1+1
  path:
  cupertino_icons: ^0.1.3
  english_words: ^3.1.5
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
